build(git-hooks): use build script as check ♻️

diff --git a/.github/hooks/pre-push b/.github/hooks/pre-push
--- a/.github/hooks/pre-push
+++ b/.github/hooks/pre-push
@@ -1,15 +1,7 @@
 #!/bin/sh
 
-FILES=$(git diff --cached --name-only --diff-filter=ACMR);
-[ -z "$FILES" ] && exit 0;
+# run build
+npx next build;
 
-# run type-check
-npx tsc --pretty --noEmit && npm run build;
-tsc_exit_code=$?;
-
-# check the tsc exit code
-if [ $tsc_exit_code -ne 0 ]; then
-  exit 1;
-fi
-
-exit 0;
+# exit code
+exit $?;
