style(git-hooks): reduce indent size :art:

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -19,8 +19,8 @@ linter_exit_code=$?;
 
 # check the linter exit code
 if [ $linter_exit_code -ne 0 ]; then
-    echo "❌  Linter errors";
-    exit 1;
+  echo "❌  Linter errors";
+  exit 1;
 fi
 
 # add back the modified/prettified files to staging
diff --git a/.github/hooks/pre-push b/.github/hooks/pre-push
--- a/.github/hooks/pre-push
+++ b/.github/hooks/pre-push
@@ -9,8 +9,8 @@ tsc_exit_code=$?;
 
 # check the tsc exit code
 if [ $tsc_exit_code -ne 0 ]; then
-    echo "❌ Typescript errors";
-    exit 1;
+  echo "❌ Typescript errors";
+  exit 1;
 fi
 
 echo "👍";
