feat(api): add middleware to authenticate api requests ✨ (#77)

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -12,15 +12,15 @@ FULLY_STAGED=$(comm -23 ".github/hooks/S.log" ".github/hooks/U.log");
 rm -f ".github/hooks/S.log" ".github/hooks/U.log";
 
 # run linters
-echo "$FILES" | grep  -E '\.(?:t|j)sx?$' | xargs ./node_modules/.bin/eslint --quiet --format stylish &&
-echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write;
+echo "$FILES" | grep  -E '\.(?:t|j)sx?$' | xargs npx eslint --quiet --format stylish &&
+echo "$FILES" | xargs npx prettier --ignore-unknown --write;
 
 linter_exit_code=$?;
 
 # check the linter exit code
 if [ $linter_exit_code -ne 0 ]; then
-    echo "❌  Linter errors";
-    exit 1;
+  echo "❌  Linter errors";
+  exit 1;
 fi
 
 # add back the modified/prettified files to staging
diff --git a/.github/hooks/pre-push b/.github/hooks/pre-push
--- a/.github/hooks/pre-push
+++ b/.github/hooks/pre-push
@@ -4,13 +4,13 @@ FILES=$(git diff --cached --name-only --diff-filter=ACMR);
 [ -z "$FILES" ] && exit 0;
 
 # run type-check
-./node_modules/.bin/tsc --pretty --noEmit;
+npx tsc --pretty --noEmit && npm run build;
 tsc_exit_code=$?;
 
 # check the tsc exit code
 if [ $tsc_exit_code -ne 0 ]; then
-    echo "❌ Typescript errors";
-    exit 1;
+  echo "❌ Typescript errors";
+  exit 1;
 fi
 
 echo "👍";
